- name: installing AUR helper
  tags: install,aur
  block:
    - name: clone the yay repository
      ansible.builtin.git:
        repo: "https://aur.archlinux.org/yay.git"
        dest: "{{ansible_env.HOME}}/src"
    
    - name: install yay
      ansible.builtin.command: "cd {{ lookup('env', HOME) }}/src/yay && makepkg -si"
