- name: installing display server
  community.general.pacman:
    name:
      - xorg
      - xorg-server
      - xorg-apps
      - xorg-xinit
      - xorg-xclock
      - lightdm
      - xdg-user-dirs
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
