- name: installing base packages
  community.general.pacman:
    name:
      - base-devel
      - python
      - python-pip
      - git

- name: Installing all the utilities
  block:
    - include_tasks: "display_server.yml"
    - include_tasks: "network_utils.yml"
    - include_tasks: "sound_system.yml"
    - include_tasks: "power.yml"
    - include_tasks: "bluetooth.yml"
    - include_tasks: "notifications.yml"
  become: true
